using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class Gestao_Gestaox : System.Web.UI.UserControl
{
    protected void Page_Load(object sender, EventArgs e)
    {
        if (!IsPostBack)
        {
            string vHabilita = "";
            string vTopNegrito = "";
            string vNovoItem = "";
            Funcoes func = new Funcoes();
            int[] funcoesAcesso = func.PegaArrayAcessosUsuario(Session["UsuarioAtual"].ToString());
            int[] funcoesTopAce = func.PegaArrayTopFuncoesUsuario(Session["UsuarioAtual"].ToString());
            int vMaxFuncao = Convert.ToInt32(func.PegaCampoPorSQL("select max(cd_funcao)-20 V_AUX from ca_funcao"));

            string vDadosFunc = func.PegaCampoPorSQL("select rtrim(lower(nm_guerra)) v_aux from funcionario where cd_pessoa = " + HttpContext.Current.Session["UsuarioAtual"].ToString()) +
                        " - " + func.PegaCampoPorSQL("select rtrim(lower(s.ds_setor)) v_aux from funcionario f, setor s where f.cd_setor = s.cd_setor and f.cd_pessoa = " + HttpContext.Current.Session["UsuarioAtual"].ToString()) +
                        " - banco: " + func.PegaCampoPorSQL("select db_name() V_AUX");
            string vImgFun = "http://www.sj.com.br/DocTrocaTitEnergia/FotosColaboradores/" + HttpContext.Current.Session["UsuarioAtual"].ToString() + ".jpg";
            //if (!File.Exists(vImgFun))
            //    vImgFun = "http://www.sj.com.br/appsgi/imagens/desconhecido.jpg";

            StringBuilder sb = new StringBuilder();
            sb.Append("<nav class='navbar navbar-expand-lg navbar-light '  style='background-color: #DADCE0;' >");
            sb.Append("<button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#conteudoNavbarSuportado' aria-controls='conteudoNavbarSuportado' aria-expanded='false' aria-label='Alterna navegação'>");
            sb.Append("<span class='navbar-toggler-icon'></span>");
            sb.Append("</button>");
            sb.Append("<a class='navbar-brand' href='#'>Sistema de Gestão</a>");
            sb.Append("<div class='collapse navbar-collapse' id='conteudoNavbarSuportado'>");
            sb.Append("<ul class='navbar-nav mr-auto'>");
            sb.Append("      <li class='nav-item active py-1 '>");
            if (Session["EmpresaAtual"].ToString() == "1" || Session["EmpresaAtual"].ToString() == "2" || Session["EmpresaAtual"].ToString() == "3" || Session["EmpresaAtual"].ToString() == "4" || Session["EmpresaAtual"].ToString() == "5" || Session["EmpresaAtual"].ToString() == "8" || Session["EmpresaAtual"].ToString() == "9")
                sb.Append(" <a class='navbar-brand' href='../../default.aspx'><img src = '../../Imagens/logohome.png'   alt='' ></a>");
            if (Session["EmpresaAtual"].ToString() == "6")
                sb.Append(" <a class='navbar-brand' href='../../defaultBlokus.aspx'><img src = '../../Imagens/logohome.png'   alt='' ></a>");
            if (Session["EmpresaAtual"].ToString() == "7")
                sb.Append(" <a class='navbar-brand' href='../../defaultVerdeGreen.aspx'><img src = '../../Imagens/logohome.png'   alt='' ></a>");
            if (Session["EmpresaAtual"].ToString() == "19")
                sb.Append(" <a class='navbar-brand' href='../../defaultReadi.aspx'><img src = '../../Imagens/logohome.png'   alt='' ></a>");
            //sb.Append("        <a class='nav-link' href='/default.aspx'>Início <span class='sr-only'>(página atual)</span></a>");
            sb.Append("      </li>");
            /*sb.Append("      <li class='nav-item'>");
            sb.Append("        <a class='nav-link' href='#'>Link</a>");
            sb.Append("      </li>");*/
            sb.Append("      <li class='nav-item dropdown'>");
            sb.Append("        <a class='nav-link dropdown-toggle' href='#' id='navbarDropdown' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>");


            //mudar a partir


            sb.Append("         &nbsp;&nbsp;Colaboradores");
            sb.Append("        </a>");
            sb.Append("        <div class='dropdown-menu' aria-labelledby='navbarDropdown'>");
            if (!funcoesAcesso.Any(x => x == 332)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 332)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (332 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_func_novo.aspx'>Cadastro Novo Colaborador Corporativo" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 319)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 319)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (319 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='ficha_colaborador.aspx'>Ficha do Colaborador Corporativo" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 16)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 16)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (16 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_func.aspx'>Cadastro e Controle de Colaborador SJ" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 17)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 17)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (17 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_dossie.aspx'>Dossiê do Colaborador" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 566)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 566)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (566 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_entrev_deslig.aspx'>Entrevista do Colaborador" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 778)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 778)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (778 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_dados_gerais_col.aspx'>Dados Gerais de Colaborador" + vNovoItem + "</a>");
            sb.Append("        </div>");
            sb.Append("      </li>");

            // Segunda Aba
            sb.Append("      <li class='nav-item dropdown'>");
            sb.Append("        <a class='nav-link dropdown-toggle' href='#' id='navbarDropdown' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>");
            sb.Append("         &nbsp;&nbsp;Sugestões");
            sb.Append("        </a>");
            sb.Append("        <div class='dropdown-menu' aria-labelledby='navbarDropdown'>");
            if (!funcoesAcesso.Any(x => x == 18)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 18)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (18 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_indicador_rotina.aspx'>Registrar Sugestão" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 19)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 19)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (19 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cons_pend_aprov_ind_rot.aspx'>Temas" + vNovoItem + "</a>");
            sb.Append("        </div>");
            sb.Append("      </li>");

            sb.Append("      <li class='nav-item dropdown'>");
            sb.Append("        <a class='nav-link dropdown-toggle' href='#' id='navbarDropdown' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>");
            sb.Append("         &nbsp;&nbsp;Treinamentos");
            sb.Append("        </a>");
            sb.Append("        <div class='dropdown-menu' aria-labelledby='navbarDropdown'>");
            if (!funcoesAcesso.Any(x => x == 20)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 20)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (20 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_treinamento.aspx?tp=2'>Solicitação de Treinamento" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 21)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 21)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (21 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_treinamento.aspx?tp=1'>Cadastro de Treinamento" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 22)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 22)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (22 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='historico_treinamento.aspx'>Histórico de Treinamento" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 23)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 23)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (23 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cons_pend_sol_treina.aspx'>Aguardando Análise" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 399)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 399)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (399 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_lnt.aspx'>Cadastro de LND" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 25)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 25)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (25 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_levantamento_nec_treinam.aspx'>Plano Anual de Treinamento" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 480)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 480)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (480 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='pend_avaliacao_reacao_treinamento.aspx'>Pendências de Avaliação de Reação" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 489)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 489)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (489 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='pend_avaliacao_eficacia_trein.aspx'>Pendências de Avaliação de Eficácia" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 719)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 719)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (719 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='folder_treinamentos.aspx'>Folder Treinamento" + vNovoItem + "</a>");
            sb.Append("        </div>");
            sb.Append("      </li>");

            sb.Append("      <li class='nav-item dropdown'>");
            sb.Append("        <a class='nav-link dropdown-toggle' href='#' id='navbarDropdown' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>");
            sb.Append("         &nbsp;&nbsp;Processo Seletivo");
            sb.Append("        </a>");
            sb.Append("        <div class='dropdown-menu' aria-labelledby='navbarDropdown'>");
            if (!funcoesAcesso.Any(x => x == 26)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 26)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (26 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_candidato.aspx'>Candidatos" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 27)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 27)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (27 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_proc_seletivo.aspx'>Processos Seletivos" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 28)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 28)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (28 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_solicitacao_vaga.aspx'>Solicitação de Vagas" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 29)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 29)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (29 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cons_pend_sol_vag.aspx'>Pendências de Autorização" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 512)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 512)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (512 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_area_int.aspx'>Hotelaria" + vNovoItem + "</a>");
            sb.Append("        </div>");
            sb.Append("      </li>");

            sb.Append("      <li class='nav-item dropdown'>");
            sb.Append("        <a class='nav-link dropdown-toggle' href='#' id='navbarDropdown' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>");
            sb.Append("         &nbsp;&nbsp;Processo Seletivo");
            sb.Append("        </a>");
            sb.Append("        <div class='dropdown-menu' aria-labelledby='navbarDropdown'>");
            if (!funcoesAcesso.Any(x => x == 111)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 111)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (111 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_tipo_modulo_estudo.aspx'>Tipos de Módulo de Estudo" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 112)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 112)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (112 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_modulo_estudo.aspx'>Cadastro de Módulos de Estudo" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 113)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 113)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (113 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_modulo_estudo_disp_leitura.aspx'>Módulos de Estudo Disponível para Leitura" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 145)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 145)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (145 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_associacao_cargo_ugb_mod_estudo.aspx'>Associação de Cargos - UGBs - Módulo de Estudo" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 146)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 146)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (146 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_prova_modulo.aspx'>Cadastro de Prova de Módulo" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 147)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 147)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (147 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='realiza_prova_modulo.aspx'>Realização de Prova" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 148)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 148)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (148 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='corrige_prova_modulo.aspx'>Correção de Prova" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 149)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 149)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (149 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='visualizacao_prova_modulo.aspx'>Visualização de Prova" + vNovoItem + "</a>");
            sb.Append("        </div>");
            sb.Append("      </li>");

            sb.Append("      <li class='nav-item dropdown'>");
            sb.Append("        <a class='nav-link dropdown-toggle' href='#' id='navbarDropdown' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>");
            sb.Append("         &nbsp;&nbsp;Pesquisas");
            sb.Append("        </a>");
            sb.Append("        <div class='dropdown-menu' aria-labelledby='navbarDropdown'>");
            if (!funcoesAcesso.Any(x => x == 327)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 327)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (327 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_avaliacao_pesquisa.aspx'>Cadastro de Pesquisas" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 328)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 328)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (328 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_perguntas_pesquisa.aspx'>Perguntas e Respostas de Pesquisa" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 331)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 331)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (331 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='responder_pesquisa.aspx'>Responder Pesquisa" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 160)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 160)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (160 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_pesquisa_satisfacao_grafico.aspx'>Gráfico de Resultado de Pesquisa" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 326)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 326)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (326 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_avaliacao_pesquisa.aspx'>Relatório de Pesquisa de Satisfação" + vNovoItem + "</a>");
            sb.Append("        </div>");
            sb.Append("      </li>");

            sb.Append("      <li class='nav-item dropdown'>");
            sb.Append("        <a class='nav-link dropdown-toggle' href='#' id='navbarDropdown' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>");
            sb.Append("         &nbsp;&nbsp;Avaliações");
            sb.Append("        </a>");

            // 1o Drop Down Comeca aqui
            sb.Append("        <a class='nav-link dropdown-toggle' href='#' id='navbarDropdown' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>");
            sb.Append("         &nbsp;&nbsp;Avaliação Colaborador");
            sb.Append("        </a>");
            sb.Append("        <div class='dropdown-menu' aria-labelledby='navbarDropdown'>");
            if (!funcoesAcesso.Any(x => x == 355)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 355)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (355 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_avaliacao_pesquisa_colaborador.aspx'>Cadastro de Avaliação de Desempenho do Colaborador" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 357)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 357)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (357 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='responder_pesquisa_colaborador.aspx'>Responder Pesquisa de Desempenho do Colaborador" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 543)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 543)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (543 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_det_aval_desemp_col_col.aspx'>Relatório de Avaliação de Desempenho de Colaborador por Colaborador - Detalhe" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 544)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 544)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (544 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_aval_desemp_col_col.aspx'>Relatório de Avaliação de Desempenho de Colaborador por Colaborador" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 545)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 545)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (545 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_aval_desemp_col_ugb.aspx'>Relatório de Avaliação de Desempenho de Colaborador por UGB" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 546)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 546)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (546 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_aval_desemp_col_empresa.aspx'>Relatório de Avaliação de Desempenho de Colaborador por Empresa" + vNovoItem + "</a>");
            sb.Append("        </div>");
            sb.Append("      </li>");

            // 2o Drop Down Comeca aqui
            sb.Append("        <a class='nav-link dropdown-toggle' href='#' id='navbarDropdown' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>");
            sb.Append("         &nbsp;&nbsp;Avaliação Colaborador");
            sb.Append("        </a>");
            sb.Append("        <div class='dropdown-menu' aria-labelledby='navbarDropdown'>");
            if (!funcoesAcesso.Any(x => x == 355)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 355)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (355 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_avaliacao_pesquisa_colaborador.aspx'>Cadastro de Avaliação de Desempenho do Colaborador" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 357)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 357)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (357 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='responder_pesquisa_colaborador.aspx'>Responder Pesquisa de Desempenho do Colaborador" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 543)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 543)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (543 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_det_aval_desemp_col_col.aspx'>Relatório de Avaliação de Desempenho de Colaborador por Colaborador - Detalhe" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 544)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 544)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (544 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_aval_desemp_col_col.aspx'>Relatório de Avaliação de Desempenho de Colaborador por Colaborador" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 545)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 545)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (545 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_aval_desemp_col_ugb.aspx'>Relatório de Avaliação de Desempenho de Colaborador por UGB" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 546)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 546)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (546 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_aval_desemp_col_empresa.aspx'>Relatório de Avaliação de Desempenho de Colaborador por Empresa" + vNovoItem + "</a>");
            sb.Append("        </div>");
            sb.Append("      </li>");


            sb.Append("      <li class='nav-item dropdown'>");
            sb.Append("        <a class='nav-link dropdown-toggle' href='#' id='navbarDropdown' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>");
            sb.Append("         &nbsp;&nbsp;Relatório");
            sb.Append("        </a>");
            sb.Append("        <div class='dropdown-menu' aria-labelledby='navbarDropdown'>");
            if (!funcoesAcesso.Any(x => x == 376)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 376)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (376 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_cargos_sal.aspx'>Cargos e Salários" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 442)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 442)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (442 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_treinamento.aspx'>Treinamentos" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 483)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 483)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (483 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_aval_reacao_trein.aspx'>Avaliação de Reação de Treinamentos" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 486)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 486)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (486 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_aval_reacao_facilitador_trein.aspx'>Avaliação de Reação de Treinamento" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 491)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 491)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (491 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_aval_eficacia_trein.aspx'>Avaliação de Eficácia de Treinamento" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 497)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 497)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (497 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_grafico_aval_reacao.aspx'>Gráfico de Avaliação de Reação de Treinamento" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 496)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 496)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (496 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_grafico_aval_reac_inst.aspx'>Gráfico de Avaliação de Treinamento - Facilitador" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 498)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 498)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (498 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_valor_gasto_trein_ugb.aspx'>Gastos de Treinamento por UGB" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 508)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 508)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (508 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_treinam_prev_real.aspx'>Treinamento Previstos x Realizados" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 574)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 574)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (574 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_qualid_selecao.aspx'>Qualidade de Seleção" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 575)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 575)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (575 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_qtd_vagas.aspx'>Quantidade de Vagas" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 576)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 576)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (576 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_tempo_medio_selecao.aspx'>Tempo Médio de Seleção" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 588)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 588)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (588 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_qtd_horas_treinam.aspx'>Quantidade de Horas por Treinamento" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 567)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 567)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (567 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_entrev_deslig.aspx'>Entrevista de Desligamento" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 682)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 682)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (682 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_modulo_estudo_provas.aspx'>Módulos de Estudos e Provas" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 761)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 761)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (761 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_perc_particip_treinam.aspx'>% de Participação em Treinamentos" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 821)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 821)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (821 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_grafico_notas_pesq_lid_pares.aspx'>Gráfico de Notas da Avaliação de Desempenho do Colaborador" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 875)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 875)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (875 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='rel_grau_instrucao.aspx'>Colaboradores por Grau de Instrução" + vNovoItem + "</a>");
            sb.Append("        </div>");
            sb.Append("      </li>");

            sb.Append("      <li class='nav-item dropdown'>");
            sb.Append("        <a class='nav-link dropdown-toggle' href='#' id='navbarDropdown' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>");
            sb.Append("         &nbsp;&nbsp;Cadastros");
            sb.Append("        </a>");
            sb.Append("        <div class='dropdown-menu' aria-labelledby='navbarDropdown'>");
            if (!funcoesAcesso.Any(x => x == 32)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 32)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (32 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_tipo_etp_proc_seletivo.aspx'>Etapas do Processo Seletivo" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 33)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 33)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (33 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_cargo.aspx'>Cargos" + vNovoItem + "</a>");
            //if (!funcoesAcesso.Any(x => x == Competências)) vHabilita = " disabled "; else vHabilita = "";
            //if (funcoesTopAce.Any(x => x == Competências)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            //if (Competências > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            //sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_tipo_competencia_requirida.aspx'>Competências" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 34)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 34)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (34 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_tipo_dossie.aspx'>Tipo de Dossiê" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 35)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 35)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (35 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_instrutor.aspx'>Instrutores" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 36)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 36)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (36 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_pergunta_aval.aspx'>Perguntas de Avaliação" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 37)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 37)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (37 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_tipo_treinamento.aspx'>Tipos de Treinamento" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 260)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 260)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (260 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_tipo_situacao_origem_opm.aspx'>Tipos de Situação Origem OPM" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 346)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 346)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (346 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_setor.aspx'>Setores" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 398)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 398)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (398 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_tipo_lnt.aspx'>Tipos de LND" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 482)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 482)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (482 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_modelo_aval_reacao.aspx'>Modelo de Avaliação de Reação" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 342)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 342)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (342 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_ugb.aspx'>UGBs" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 553)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 553)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (553 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_relac_ugbs.aspx'>Relacionamento entre UGBs" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 565)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 565)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (565 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_item_entrev_deslig.aspx'>Itens de Entrevista de Desligamento" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 675)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 675)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (675 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_pasta_doc_func.aspx'Tipos de Pasta de Documento do Colaborador" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 952)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 952)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (952 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_motivo_nao_conformidade_colab.aspx'>Motivos de Não Conformidade de Colaborador" + vNovoItem + " </a>");
            if (!funcoesAcesso.Any(x => x == 1219)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 1219)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (1219> vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_pergunta_qse.aspx'>Perguntas QSE" + vNovoItem + "</a>");
            if (!funcoesAcesso.Any(x => x == 1272)) vHabilita = " disabled "; else vHabilita = "";
            if (funcoesTopAce.Any(x => x == 1272)) vTopNegrito = " font-weight-bold "; else vTopNegrito = "";
            if (1272 > vMaxFuncao) vNovoItem = "<sup>novo<sup>"; else vNovoItem = "";
            sb.Append("          <a class='dropdown-item " + vTopNegrito + vHabilita + "' href='cad_plantao.aspx'>Colaboradores de 8g às 18h" + vNovoItem + "</a>");
           

            sb.Append("        </div>");
            sb.Append("      </li>");


            sb.Append("      <li class='nav-item'>");
            sb.Append(" <a class='nav-link disabled' href='#'>&nbsp;&nbsp;&nbsp;</a>");
            sb.Append("      </li>");
            sb.Append("<li class='nav-item align-bottom  py-1'>");
            sb.Append(" <a class='navbar-brand align-bottom' href='../../Comum/cad_imovel.aspx' target='_blank' tooltipo='imóvel'>");
            sb.Append("    <img src = '../../Imagens/mnimovelx.png'   alt='' >");
            sb.Append("  </a>");
            sb.Append(" <a class='navbar-brand' href='../../Comum/cad_contrato.aspx' target='_blank'>");
            sb.Append("    <img src = '../../Imagens/mncontratox.png'   alt='' >");
            sb.Append("  </a>");
            sb.Append(" <a class='navbar-brand' href='../../Comum/cad_proprietario.aspx' target='_blank'>");
            sb.Append("    <img src = '../../Imagens/mnproprietariox.png'   alt='' >");
            sb.Append("  </a>");
            sb.Append(" <a class='navbar-brand' href='../../Tesouraria/Paginas/consulta_recibo.aspx' target='_blank'>");
            sb.Append("    <img src = '../../Imagens/mnrecibox.png'   alt='' >");
            sb.Append("  </a>");
            sb.Append("</li>");
            sb.Append(" <a class='navbar-brand' href='#'>");
            sb.Append("    <img src = '" + vImgFun + "' width='30' height='30' alt='' title='" + vDadosFunc + "' class='rounded'>");
            sb.Append("  </a>");
            sb.Append("    </ul>");
            /*sb.Append("    <form class='form-inline my-2 my-lg-0'>");
            sb.Append(" <input class='form-control mr-sm-2' type='search' placeholder='Pesquisar' aria-label='Pesquisar'>");
            sb.Append("      <button class='btn btn-outline-success my-2 my-sm-0' type='submit'>Pesquisar</button>");
            sb.Append("    </form>");*/
            sb.Append("  </div>");
            sb.Append("</nav>");
            myNav.InnerHtml = sb.ToString();
        }
    }
}