export { default as Pronome } from "@/utils/Diversity/pronome"
export { default as Escolaridade } from "@/utils/escolaridade"
export { default as Genero } from "@/utils/Diversity/genero"
export { default as IdentidadeGenero } from "@/utils/Diversity/identidade"
export { default as Etnia } from "@/utils/Diversity/etnia"
export { default as Naturalidade } from "@/utils/Diversity/naturalidade"
export { default as OrientacaoSexual } from "@/utils/Diversity/orientacao"