const Skills = [
  { id: 0, desc: "Selecione suas skills", value: "null" },
  { id: 1, desc: "ABAP", value: "ABAP" },
  { id: 2, desc: "ABNF", value: "ABNF" },
  { id: 3, desc: "Ada", value: "Ada" },
  {
    id: 4,
    desc: "Administrador de sistema",
    value: "Administrador de sistema"
  },
  { id: 5, desc: "AdonisJS", value: "AdonisJS" },
  { id: 6, desc: "ADVPL", value: "ADVPL" },
  { id: 7, desc: "ADVPL ASP", value: "ADVPL ASP" },
  { id: 8, desc: "Agavi", value: "Agavi" },
  { id: 9, desc: "Agda", value: "Agda" },
  { id: 10, desc: "AgilePHP", value: "AgilePHP" },
  { id: 11, desc: "AGS Script", value: "AGS Script" },
  { id: 12, desc: "Ajax", value: "Ajax" },
  { id: 13, desc: "Akelos", value: "Akelos" },
  { id: 14, desc: "Alloy", value: "Alloy" },
  { id: 15, desc: "Alpine Abuild", value: "Alpine Abuild" },
  { id: 16, desc: "AMPL", value: "AMPL" },
  { id: 17, desc: "Android", value: "Android" },
  { id: 18, desc: "Android Studio", value: "Android Studio" },
  { id: 19, desc: "Angular", value: "Angular" },
  { id: 20, desc: "Ant Build System", value: "Ant Build System" },
  { id: 21, desc: "ANTLR", value: "ANTLR" },
  { id: 22, desc: "Apache", value: "Apache" },
  { id: 23, desc: "Apex", value: "Apex" },
  { id: 24, desc: "API", value: "API" },
  { id: 25, desc: "APL", value: "APL" },
  {
    id: 26,
    desc: "Apollo Guidance Computer",
    value: "Apollo Guidance Computer"
  },
  { id: 27, desc: "AppleScript", value: "AppleScript" },
  { id: 28, desc: "Arc", value: "Arc" },
  { id: 29, desc: "Arduino", value: "Arduino" },
  { id: 30, desc: "ARKit", value: "ARKit" },
  { id: 31, desc: "AsciiDoc", value: "AsciiDoc" },
  { id: 32, desc: "ASN.1", value: "ASN.1" },
  { id: 33, desc: "ASP", value: "ASP" },
  { id: 34, desc: "AspectJ", value: "AspectJ" },
  { id: 35, desc: "ASP.NET", value: "ASP.NET" },
  { id: 36, desc: "ASP.NET Core", value: "ASP.NET Core" },
  { id: 37, desc: "ASP.NET MVC", value: "ASP.NET MVC" },
  { id: 38, desc: "Assembly", value: "Assembly" },
  { id: 39, desc: "Atomik", value: "Atomik" },
  { id: 40, desc: "ATS", value: "ATS" },
  { id: 41, desc: "Augeas", value: "Augeas" },
  { id: 42, desc: "Aura", value: "Aura" },
  { id: 43, desc: "Aurelia", value: "Aurelia" },
  { id: 44, desc: "AutoHotkey", value: "AutoHotkey" },
  { id: 45, desc: "AutoIt", value: "AutoIt" },
  { id: 46, desc: "Awk", value: "Awk" },
  {
    id: 47,
    desc: "AWS EC2 (Elastic Compute Cloud)",
    value: "AWS EC2 (Elastic Compute Cloud)"
  },
  {
    id: 48,
    desc: "AWS RDS (Relational Database Service)",
    value: "AWS RDS (Relational Database Service)"
  },
  { id: 49, desc: "AWS S3", value: "AWS S3" },
  { id: 50, desc: "Azure", value: "Azure" },
  { id: 51, desc: "Backbone.js", value: "Backbone.js" },
  { id: 52, desc: "Backendless", value: "Backendless" },
  { id: 53, desc: "Bash", value: "Bash" },
  { id: 54, desc: "Batchfile", value: "Batchfile" },
  { id: 55, desc: "Beego", value: "Beego" },
  { id: 56, desc: "Befunge", value: "Befunge" },
  { id: 57, desc: "Big Data", value: "Big Data" },
  { id: 58, desc: "Bison", value: "Bison" },
  { id: 59, desc: "BitBake", value: "BitBake" },
  { id: 60, desc: "Blade", value: "Blade" },
  { id: 61, desc: "BlitzBasic", value: "BlitzBasic" },
  { id: 62, desc: "BlitzMax", value: "BlitzMax" },
  { id: 63, desc: "Blockchain", value: "Blockchain" },
  { id: 64, desc: "Bluespec", value: "Bluespec" },
  { id: 65, desc: "Boo", value: "Boo" },
  { id: 66, desc: "Bootstrap", value: "Bootstrap" },
  { id: 67, desc: "Bottle", value: "Bottle" },
  { id: 68, desc: "Brainfuck", value: "Brainfuck" },
  { id: 69, desc: "Brightscript", value: "Brightscript" },
  { id: 70, desc: "Bro", value: "Bro" },
  { id: 71, desc: "Brutos", value: "Brutos" },
  { id: 72, desc: "C", value: "C" },
  { id: 73, desc: "C#", value: "C#" },
  { id: 74, desc: "C++", value: "C++" },
  { id: 75, desc: "C2hs Haskell", value: "C2hs Haskell" },
  { id: 76, desc: "Cairngorm", value: "Cairngorm" },
  { id: 77, desc: "CakePHP", value: "CakePHP" },
  { id: 78, desc: "Camping", value: "Camping" },
  { id: 79, desc: "Cappuccino", value: "Cappuccino" },
  { id: 80, desc: "CartoCSS", value: "CartoCSS" },
  { id: 81, desc: "Catalyst", value: "Catalyst" },
  { id: 82, desc: "Ceylon", value: "Ceylon" },
  { id: 83, desc: "CGI Application", value: "CGI Application" },
  { id: 84, desc: "CGI Prototype", value: "CGI Prototype" },
  { id: 85, desc: "Chapel", value: "Chapel" },
  { id: 86, desc: "Charity", value: "Charity" },
  { id: 87, desc: "CherryPy", value: "CherryPy" },
  { id: 88, desc: "ChucK", value: "ChucK" },
  { id: 89, desc: "Circumflex", value: "Circumflex" },
  { id: 90, desc: "Cirru", value: "Cirru" },
  { id: 91, desc: "Clarion", value: "Clarion" },
  { id: 92, desc: "Clean", value: "Clean" },
  { id: 93, desc: "Clean Code", value: "Clean Code" },
  { id: 94, desc: "ClearPress", value: "ClearPress" },
  { id: 95, desc: "Click", value: "Click" },
  { id: 96, desc: "CLIPS", value: "CLIPS" },
  { id: 97, desc: "Clojure", value: "Clojure" },
  { id: 98, desc: "Cloud", value: "Cloud" },
  { id: 99, desc: "CMake", value: "CMake" },
  { id: 100, desc: "C-ObjDump", value: "C-ObjDump" },
  { id: 101, desc: "COBOL", value: "COBOL" },
  { id: 102, desc: "Cocoon", value: "Cocoon" },
  { id: 103, desc: "CodeIgniter", value: "CodeIgniter" },
  { id: 104, desc: "CoffeeScript", value: "CoffeeScript" },
  { id: 105, desc: "ColdFusion", value: "ColdFusion" },
  { id: 106, desc: "ColdFusion CFC", value: "ColdFusion CFC" },
  { id: 107, desc: "COLLADA", value: "COLLADA" },
  { id: 108, desc: "Common Lisp", value: "Common Lisp" },
  { id: 109, desc: "Compojure", value: "Compojure" },
  { id: 110, desc: "Component Pascal", value: "Component Pascal" },
  { id: 111, desc: "CompoundJS", value: "CompoundJS" },
  { id: 112, desc: "Conjure", value: "Conjure" },
  { id: 113, desc: "Continuous Delivery", value: "Continuous Delivery" },
  { id: 114, desc: "Continuous Integration", value: "Continuous Integration" },
  { id: 115, desc: "Cool", value: "Cool" },
  { id: 116, desc: "Coq", value: "Coq" },
  { id: 117, desc: "Cordova", value: "Cordova" },
  { id: 118, desc: "Cpp-ObjDump", value: "Cpp-ObjDump" },
  { id: 119, desc: "Creole", value: "Creole" },
  { id: 120, desc: "Crystal", value: "Crystal" },
  { id: 121, desc: "CSON", value: "CSON" },
  { id: 122, desc: "Csound", value: "Csound" },
  { id: 123, desc: "Csound Document", value: "Csound Document" },
  { id: 124, desc: "Csound Score", value: "Csound Score" },
  { id: 125, desc: "CSS", value: "CSS" },
  { id: 126, desc: "CSV", value: "CSV" },
  { id: 127, desc: "Cuba", value: "Cuba" },
  { id: 128, desc: "Cucumber", value: "Cucumber" },
  { id: 129, desc: "Cuda", value: "Cuda" },
  { id: 130, desc: "Cutelyst", value: "Cutelyst" },
  { id: 131, desc: "Cyclone3", value: "Cyclone3" },
  { id: 132, desc: "Cycript", value: "Cycript" },
  { id: 133, desc: "Cypress.io", value: "Cypress.io" },
  { id: 134, desc: "Cython", value: "Cython" },
  { id: 135, desc: "D", value: "D" },
  { id: 136, desc: "Darcs Patch", value: "Darcs Patch" },
  { id: 137, desc: "Dart", value: "Dart" },
  { id: 138, desc: "Data science", value: "Data science" },
  { id: 139, desc: "DB2", value: "DB2" },
  { id: 140, desc: "Delphi", value: "Delphi" },
  { id: 141, desc: "Demandware", value: "Demandware" },
  { id: 142, desc: "Design Pattern", value: "Design Pattern" },
  { id: 143, desc: "desktop", value: "desktop" },
  { id: 144, desc: "DevOps", value: "DevOps" },
  { id: 145, desc: "Diff", value: "Diff" },
  {
    id: 146,
    desc: "DIGITAL Command Language",
    value: "DIGITAL Command Language"
  },
  { id: 147, desc: "Django", value: "Django" },
  { id: 148, desc: "DM", value: "DM" },
  { id: 149, desc: "DNS Zone", value: "DNS Zone" },
  { id: 150, desc: "D-ObjDump", value: "D-ObjDump" },
  { id: 151, desc: "Docker", value: "Docker" },
  { id: 152, desc: "Dockerfile", value: "Dockerfile" },
  { id: 153, desc: "Doctrine", value: "Doctrine" },
  { id: 154, desc: "Dogescript", value: "Dogescript" },
  { id: 155, desc: "Dojo", value: "Dojo" },
  { id: 156, desc: "Dropwizard", value: "Dropwizard" },
  { id: 157, desc: "Drupal", value: "Drupal" },
  { id: 158, desc: "DTrace", value: "DTrace" },
  { id: 159, desc: "Durandal", value: "Durandal" },
  { id: 160, desc: "Dylan", value: "Dylan" },
  { id: 161, desc: "DynamoDB", value: "DynamoDB" },
  { id: 162, desc: "E", value: "E" },
  { id: 163, desc: "Eagle", value: "Eagle" },
  { id: 164, desc: "EBNF", value: "EBNF" },
  { id: 165, desc: "eC", value: "eC" },
  { id: 166, desc: "Ecere Projects", value: "Ecere Projects" },
  { id: 167, desc: "echo", value: "echo" },
  { id: 168, desc: "ECL", value: "ECL" },
  { id: 169, desc: "ECLiPSe", value: "ECLiPSe" },
  { id: 170, desc: "edn", value: "edn" },
  { id: 171, desc: "Eiffel", value: "Eiffel" },
  { id: 172, desc: "EJB", value: "EJB" },
  { id: 173, desc: "EJS", value: "EJS" },
  { id: 174, desc: "Elasticsearch", value: "Elasticsearch" },
  { id: 175, desc: "Eliom", value: "Eliom" },
  { id: 176, desc: "Elixir", value: "Elixir" },
  { id: 177, desc: "Elm", value: "Elm" },
  { id: 178, desc: "Emacs Lisp", value: "Emacs Lisp" },
  { id: 179, desc: "Ember.js", value: "Ember.js" },
  { id: 180, desc: "EmberScript", value: "EmberScript" },
  { id: 181, desc: "Entity framework", value: "Entity framework" },
  { id: 182, desc: "EQ", value: "EQ" },
  { id: 183, desc: "Erlang", value: "Erlang" },
  { id: 184, desc: "Erlang Web", value: "Erlang Web" },
  { id: 185, desc: "ErlyWeb", value: "ErlyWeb" },
  { id: 186, desc: "ERP", value: "ERP" },
  { id: 187, desc: "ES6", value: "ES6" },
  { id: 188, desc: "Excel", value: "Excel" },
  { id: 189, desc: "Express", value: "Express" },
  { id: 190, desc: "eXtreme Programming", value: "eXtreme Programming" },
  { id: 191, desc: "F#", value: "F#" },
  { id: 192, desc: "Factor", value: "Factor" },
  { id: 193, desc: "Fancy", value: "Fancy" },
  { id: 194, desc: "Fantom", value: "Fantom" },
  { id: 195, desc: "Feathers", value: "Feathers" },
  { id: 196, desc: "Figma", value: "Figma" },
  { id: 197, desc: "Filebench WML", value: "Filebench WML" },
  { id: 198, desc: "Filterscript", value: "Filterscript" },
  { id: 199, desc: "Firebase", value: "Firebase" },
  { id: 200, desc: "Firebird", value: "Firebird" },
  { id: 201, desc: "fish", value: "fish" },
  { id: 202, desc: "Flask", value: "Flask" },
  { id: 203, desc: "Flatiron", value: "Flatiron" },
  { id: 204, desc: "Flex", value: "Flex" },
  { id: 205, desc: "Flight", value: "Flight" },
  { id: 206, desc: "Flutter", value: "Flutter" },
  { id: 207, desc: "FLUX", value: "FLUX" },
  { id: 208, desc: "Formatted", value: "Formatted" },
  { id: 209, desc: "Forth", value: "Forth" },
  { id: 210, desc: "FORTRAN", value: "FORTRAN" },
  { id: 211, desc: "FreeMarker", value: "FreeMarker" },
  { id: 212, desc: "Frege", value: "Frege" },
  { id: 213, desc: "FuelPHP", value: "FuelPHP" },
  { id: 214, desc: "Game Maker Language", value: "Game Maker Language" },
  { id: 215, desc: "GAMS", value: "GAMS" },
  { id: 216, desc: "Gantry", value: "Gantry" },
  { id: 217, desc: "GAP", value: "GAP" },
  { id: 218, desc: "GAS", value: "GAS" },
  {
    id: 219,
    desc: "GCC Machine Description",
    value: "GCC Machine Description"
  },
  { id: 220, desc: "G-code", value: "G-code" },
  { id: 221, desc: "GDB", value: "GDB" },
  { id: 222, desc: "GDScript", value: "GDScript" },
  { id: 223, desc: "Genshi", value: "Genshi" },
  { id: 224, desc: "Gentoo Ebuild", value: "Gentoo Ebuild" },
  { id: 225, desc: "Gentoo Eclass", value: "Gentoo Eclass" },
  { id: 226, desc: "Gettext Catalog", value: "Gettext Catalog" },
  { id: 227, desc: "Gin", value: "Gin" },
  { id: 228, desc: "Git", value: "Git" },
  { id: 229, desc: "GLSL", value: "GLSL" },
  { id: 230, desc: "Glyph", value: "Glyph" },
  { id: 231, desc: "GN", value: "GN" },
  { id: 232, desc: "Gnuplot", value: "Gnuplot" },
  { id: 233, desc: "Go", value: "Go" },
  { id: 234, desc: "Golo", value: "Golo" },
  { id: 235, desc: "Google Analytics", value: "Google Analytics" },
  { id: 236, desc: "Google Cloud", value: "Google Cloud" },
  { id: 237, desc: "Google Web Toolkit", value: "Google Web Toolkit" },
  { id: 238, desc: "Gosu", value: "Gosu" },
  { id: 239, desc: "Grace", value: "Grace" },
  { id: 240, desc: "Gradle", value: "Gradle" },
  { id: 241, desc: "Grails", value: "Grails" },
  { id: 242, desc: "Grain", value: "Grain" },
  { id: 243, desc: "Grammatical Framework", value: "Grammatical Framework" },
  {
    id: 244,
    desc: "Graph Modeling Language",
    value: "Graph Modeling Language"
  },
  { id: 245, desc: "GraphQL", value: "GraphQL" },
  { id: 246, desc: "Graphviz (DOT)", value: "Graphviz (DOT)" },
  { id: 247, desc: "Groff", value: "Groff" },
  { id: 248, desc: "Grok", value: "Grok" },
  { id: 249, desc: "Groovy", value: "Groovy" },
  { id: 250, desc: "Groovy Server Pages", value: "Groovy Server Pages" },
  { id: 251, desc: "Gulp", value: "Gulp" },
  { id: 252, desc: "GWT ", value: "GWT " },
  { id: 253, desc: "Hack", value: "Hack" },
  { id: 254, desc: "Halcyon", value: "Halcyon" },
  { id: 255, desc: "Haml", value: "Haml" },
  { id: 256, desc: "Hanami", value: "Hanami" },
  { id: 257, desc: "Handlebars", value: "Handlebars" },
  { id: 258, desc: "Happstack", value: "Happstack" },
  { id: 259, desc: "Harbour", value: "Harbour" },
  { id: 260, desc: "Haskell", value: "Haskell" },
  { id: 261, desc: "Haxe", value: "Haxe" },
  { id: 262, desc: "HCL", value: "HCL" },
  { id: 263, desc: "Hemlock", value: "Hemlock" },
  { id: 264, desc: "Heroku", value: "Heroku" },
  { id: 265, desc: "Hibernate", value: "Hibernate" },
  { id: 266, desc: "HLSL", value: "HLSL" },
  { id: 267, desc: "Horde", value: "Horde" },
  { id: 268, desc: "HTML", value: "HTML" },
  { id: 269, desc: "HTTP", value: "HTTP" },
  { id: 270, desc: "Hy", value: "Hy" },
  { id: 271, desc: "HybridJava", value: "HybridJava" },
  { id: 272, desc: "Hybris", value: "Hybris" },
  { id: 273, desc: "HydraMVC", value: "HydraMVC" },
  { id: 274, desc: "HyPhy", value: "HyPhy" },
  { id: 275, desc: "IDL", value: "IDL" },
  { id: 276, desc: "Idris", value: "Idris" },
  { id: 277, desc: "IGOR Pro", value: "IGOR Pro" },
  { id: 278, desc: "Inform 7", value: "Inform 7" },
  { id: 279, desc: "INI", value: "INI" },
  { id: 280, desc: "Inno Setup", value: "Inno Setup" },
  { id: 281, desc: "Io", value: "Io" },
  { id: 282, desc: "Ioke", value: "Ioke" },
  { id: 283, desc: "Ionic", value: "Ionic" },
  { id: 284, desc: "iOS", value: "iOS" },
  { id: 285, desc: "IRC log", value: "IRC log" },
  { id: 286, desc: "Ireport", value: "Ireport" },
  { id: 287, desc: "Isabelle", value: "Isabelle" },
  { id: 288, desc: "Isabelle ROOT", value: "Isabelle ROOT" },
  { id: 289, desc: "J", value: "J" },
  { id: 290, desc: "Jade", value: "Jade" },
  { id: 291, desc: "Jasmin", value: "Jasmin" },
  { id: 292, desc: "Jasper", value: "Jasper" },
  { id: 293, desc: "Java", value: "Java" },
  { id: 294, desc: "JavaEE", value: "JavaEE" },
  { id: 295, desc: "JavaScript", value: "JavaScript" },
  { id: 296, desc: "JavaScriptMVC", value: "JavaScriptMVC" },
  { id: 297, desc: "Java Server Pages", value: "Java Server Pages" },
  { id: 298, desc: "Jenkins ", value: "Jenkins " },
  { id: 299, desc: "Jest", value: "Jest" },
  { id: 300, desc: "JFlex", value: "JFlex" },
  { id: 301, desc: "Jifty", value: "Jifty" },
  { id: 302, desc: "jQuery", value: "jQuery" },
  { id: 303, desc: "JSF", value: "JSF" },
  { id: 304, desc: "JSON", value: "JSON" },
  { id: 305, desc: "JSX", value: "JSX" },
  { id: 306, desc: "Julia", value: "Julia" },
  { id: 307, desc: "JUnit", value: "JUnit" },
  { id: 308, desc: "Jupyter Notebook", value: "Jupyter Notebook" },
  { id: 309, desc: "Kanban", value: "Kanban" },
  { id: 310, desc: "KiCad", value: "KiCad" },
  { id: 311, desc: "Kit", value: "Kit" },
  { id: 312, desc: "Koa", value: "Koa" },
  { id: 313, desc: "Kohana", value: "Kohana" },
  { id: 314, desc: "Konstrukt", value: "Konstrukt" },
  { id: 315, desc: "Kotlin", value: "Kotlin" },
  { id: 316, desc: "KRL", value: "KRL" },
  { id: 317, desc: "kubernetes", value: "kubernetes" },
  { id: 318, desc: "KumbiaPHP", value: "KumbiaPHP" },
  { id: 319, desc: "LabVIEW", value: "LabVIEW" },
  { id: 320, desc: "Laravel", value: "Laravel" },
  { id: 321, desc: "Lasso", value: "Lasso" },
  { id: 322, desc: "Latte", value: "Latte" },
  { id: 323, desc: "Lean", value: "Lean" },
  { id: 324, desc: "Lemmachine", value: "Lemmachine" },
  { id: 325, desc: "Less", value: "Less" },
  { id: 326, desc: "Lex", value: "Lex" },
  { id: 327, desc: "LFE", value: "LFE" },
  { id: 328, desc: "Lift", value: "Lift" },
  { id: 329, desc: "LilyPond", value: "LilyPond" },
  { id: 330, desc: "Limbo", value: "Limbo" },
  { id: 331, desc: "Linker Script", value: "Linker Script" },
  { id: 332, desc: "Linux", value: "Linux" },
  { id: 333, desc: "Linux Kernel Module", value: "Linux Kernel Module" },
  { id: 334, desc: "Liquid", value: "Liquid" },
  { id: 335, desc: "LiquidLava", value: "LiquidLava" },
  { id: 336, desc: "Literate Agda", value: "Literate Agda" },
  { id: 337, desc: "Literate CoffeeScript", value: "Literate CoffeeScript" },
  { id: 338, desc: "Literate Haskell", value: "Literate Haskell" },
  { id: 339, desc: "Lithium", value: "Lithium" },
  { id: 340, desc: "LiveScript", value: "LiveScript" },
  { id: 341, desc: "LLVM", value: "LLVM" },
  { id: 342, desc: "Logos", value: "Logos" },
  { id: 343, desc: "Logtalk", value: "Logtalk" },
  { id: 344, desc: "LOLCODE", value: "LOLCODE" },
  { id: 345, desc: "LookML", value: "LookML" },
  { id: 346, desc: "LoomScript", value: "LoomScript" },
  { id: 347, desc: "LSL", value: "LSL" },
  { id: 348, desc: "Lua", value: "Lua" },
  { id: 349, desc: "LUMEN", value: "LUMEN" },
  { id: 350, desc: "M", value: "M" },
  { id: 351, desc: "M4", value: "M4" },
  { id: 352, desc: "M4Sugar", value: "M4Sugar" },
  { id: 353, desc: "Machine learning", value: "Machine learning" },
  { id: 354, desc: "Mack", value: "Mack" },
  { id: 355, desc: "Magento", value: "Magento" },
  { id: 356, desc: "Makefile", value: "Makefile" },
  { id: 357, desc: "Mako", value: "Mako" },
  { id: 358, desc: "MariaDB", value: "MariaDB" },
  { id: 359, desc: "Markdown", value: "Markdown" },
  { id: 360, desc: "Martini", value: "Martini" },
  { id: 361, desc: "Mask", value: "Mask" },
  { id: 362, desc: "Mason", value: "Mason" },
  { id: 363, desc: "Mate", value: "Mate" },
  { id: 364, desc: "Mathematica", value: "Mathematica" },
  { id: 365, desc: "Matlab", value: "Matlab" },
  { id: 366, desc: "Maven POM", value: "Maven POM" },
  { id: 367, desc: "Maveric", value: "Maveric" },
  { id: 368, desc: "Max", value: "Max" },
  { id: 369, desc: "MAXScript", value: "MAXScript" },
  { id: 370, desc: "MediaWiki", value: "MediaWiki" },
  { id: 371, desc: "Merb", value: "Merb" },
  { id: 372, desc: "Mercury", value: "Mercury" },
  { id: 373, desc: "Metal", value: "Metal" },
  { id: 374, desc: "Meteor", value: "Meteor" },
  { id: 375, desc: "MFlow", value: "MFlow" },
  { id: 376, desc: "miku", value: "miku" },
  { id: 377, desc: "MiniD", value: "MiniD" },
  { id: 378, desc: "Mirah", value: "Mirah" },
  { id: 379, desc: "Mithril", value: "Mithril" },
  { id: 380, desc: "Modelica", value: "Modelica" },
  { id: 381, desc: "Modula-2", value: "Modula-2" },
  {
    id: 382,
    desc: "Module Management System",
    value: "Module Management System"
  },
  { id: 383, desc: "Mojolicious", value: "Mojolicious" },
  { id: 384, desc: "MongoDB", value: "MongoDB" },
  { id: 385, desc: "Monkey", value: "Monkey" },
  { id: 386, desc: "Moocode", value: "Moocode" },
  { id: 387, desc: "MoonScript", value: "MoonScript" },
  { id: 388, desc: "Moustache", value: "Moustache" },
  { id: 389, desc: "MQL4", value: "MQL4" },
  { id: 390, desc: "MQL5", value: "MQL5" },
  { id: 391, desc: "MTML", value: "MTML" },
  { id: 392, desc: "MUF", value: "MUF" },
  { id: 393, desc: "mupad", value: "mupad" },
  { id: 394, desc: "MVC", value: "MVC" },
  { id: 395, desc: "MVVM", value: "MVVM" },
  { id: 396, desc: "Myghty", value: "Myghty" },
  { id: 397, desc: "MySQL", value: "MySQL" },
  { id: 398, desc: "Nancy", value: "Nancy" },
  { id: 399, desc: "NCL", value: "NCL" },
  { id: 400, desc: "Nemerle", value: "Nemerle" },
  { id: 401, desc: "Nerve", value: "Nerve" },
  { id: 402, desc: "nesC", value: "nesC" },
  { id: 403, desc: ".NET", value: ".NET" },
  { id: 404, desc: ".NET Core", value: ".NET Core" },
  { id: 405, desc: "NetLinx", value: "NetLinx" },
  { id: 406, desc: "NetLinx+ERB", value: "NetLinx+ERB" },
  { id: 407, desc: "NetLogo", value: "NetLogo" },
  { id: 408, desc: ".NET MVC", value: ".NET MVC" },
  { id: 409, desc: "NewLisp", value: "NewLisp" },
  { id: 410, desc: "NextJS", value: "NextJS" },
  { id: 411, desc: "Nginx", value: "Nginx" },
  { id: 412, desc: "Nimrod", value: "Nimrod" },
  { id: 413, desc: "Ninja", value: "Ninja" },
  { id: 414, desc: "Nit", value: "Nit" },
  { id: 415, desc: "Nitro", value: "Nitro" },
  { id: 416, desc: "Nix", value: "Nix" },
  { id: 417, desc: "NL", value: "NL" },
  { id: 418, desc: "Node.js", value: "Node.js" },
  { id: 419, desc: "Nodemachine", value: "Nodemachine" },
  { id: 420, desc: "Node-router", value: "Node-router" },
  { id: 421, desc: "Noir", value: "Noir" },
  { id: 422, desc: "NoSQL", value: "NoSQL" },
  { id: 423, desc: "NPM", value: "NPM" },
  { id: 424, desc: "NSIS", value: "NSIS" },
  { id: 425, desc: "Nu", value: "Nu" },
  { id: 426, desc: "NumPy", value: "NumPy" },
  { id: 427, desc: "ObjDump", value: "ObjDump" },
  { id: 428, desc: "Objective-C", value: "Objective-C" },
  { id: 429, desc: "Objective-C++", value: "Objective-C++" },
  { id: 430, desc: "Objective-J", value: "Objective-J" },
  { id: 431, desc: "OCaml", value: "OCaml" },
  { id: 432, desc: "Odoo", value: "Odoo" },
  { id: 433, desc: "Omgrofl", value: "Omgrofl" },
  { id: 434, desc: "Ooc", value: "Ooc" },
  { id: 435, desc: "Opa", value: "Opa" },
  { id: 436, desc: "Opal", value: "Opal" },
  { id: 437, desc: "OpenCL", value: "OpenCL" },
  { id: 438, desc: "OpenCV", value: "OpenCV" },
  { id: 439, desc: "OpenEdge ABL", value: "OpenEdge ABL" },
  { id: 440, desc: "OpenRC runscript", value: "OpenRC runscript" },
  { id: 441, desc: "OpenSCAD", value: "OpenSCAD" },
  { id: 442, desc: "OpenType Feature File", value: "OpenType Feature File" },
  { id: 443, desc: "OpenUI5", value: "OpenUI5" },
  { id: 444, desc: "ORACLE", value: "ORACLE" },
  { id: 445, desc: "Orbit", value: "Orbit" },
  { id: 446, desc: "Org", value: "Org" },
  { id: 447, desc: "Ox", value: "Ox" },
  { id: 448, desc: "Oxygene", value: "Oxygene" },
  { id: 449, desc: "Oz", value: "Oz" },
  { id: 450, desc: "Pan", value: "Pan" },
  { id: 451, desc: "Pandas", value: "Pandas" },
  { id: 452, desc: "Papyrus", value: "Papyrus" },
  { id: 453, desc: "Parrot", value: "Parrot" },
  { id: 454, desc: "Parrot Assembly", value: "Parrot Assembly" },
  {
    id: 455,
    desc: "Parrot Internal Representation",
    value: "Parrot Internal Representation"
  },
  { id: 456, desc: "Pascal", value: "Pascal" },
  { id: 457, desc: "PAWN", value: "PAWN" },
  { id: 458, desc: "PeopleCode", value: "PeopleCode" },
  { id: 459, desc: "Perfect", value: "Perfect" },
  { id: 460, desc: "Perl", value: "Perl" },
  { id: 461, desc: "Perl6", value: "Perl6" },
  { id: 462, desc: "Phalcon", value: "Phalcon" },
  { id: 463, desc: "Phoenix", value: "Phoenix" },
  { id: 464, desc: "PhoneGap", value: "PhoneGap" },
  { id: 465, desc: "Photoshop", value: "Photoshop" },
  { id: 466, desc: "PHP", value: "PHP" },
  { id: 467, desc: "PHPUnit", value: "PHPUnit" },
  { id: 468, desc: "Pic", value: "Pic" },
  { id: 469, desc: "Picard", value: "Picard" },
  { id: 470, desc: "Pickle", value: "Pickle" },
  { id: 471, desc: "PicoLisp", value: "PicoLisp" },
  { id: 472, desc: "PigLatin", value: "PigLatin" },
  { id: 473, desc: "Pike", value: "Pike" },
  { id: 474, desc: "Play", value: "Play" },
  { id: 475, desc: "PLpgSQL", value: "PLpgSQL" },
  { id: 476, desc: "PLSQL", value: "PLSQL" },
  { id: 477, desc: "Pod", value: "Pod" },
  { id: 478, desc: "PogoScript", value: "PogoScript" },
  { id: 479, desc: "Polymer", value: "Polymer" },
  { id: 480, desc: "Pony", value: "Pony" },
  { id: 481, desc: "POO", value: "POO" },
  { id: 482, desc: "PostgreSQL", value: "PostgreSQL" },
  { id: 483, desc: "PostScript", value: "PostScript" },
  { id: 484, desc: "POV-Ray SDL", value: "POV-Ray SDL" },
  { id: 485, desc: "PowerBuilder", value: "PowerBuilder" },
  { id: 486, desc: "PowerShell", value: "PowerShell" },
  { id: 487, desc: "Prado", value: "Prado" },
  { id: 488, desc: "Processing", value: "Processing" },
  { id: 489, desc: "Progress", value: "Progress" },
  { id: 490, desc: "Prolog", value: "Prolog" },
  { id: 491, desc: "Propeller Spin", value: "Propeller Spin" },
  { id: 492, desc: "Protocol Buffer", value: "Protocol Buffer" },
  { id: 493, desc: "Public Key", value: "Public Key" },
  { id: 494, desc: "Puppet", value: "Puppet" },
  { id: 495, desc: "PureBasic", value: "PureBasic" },
  { id: 496, desc: "Pure Data", value: "Pure Data" },
  { id: 497, desc: "PureMVC", value: "PureMVC" },
  { id: 498, desc: "PureScript", value: "PureScript" },
  { id: 499, desc: "PWA", value: "PWA" },
  { id: 500, desc: "Pyramid", value: "Pyramid" },
  { id: 501, desc: "PyTest", value: "PyTest" },
  { id: 502, desc: "Python", value: "Python" },
  { id: 503, desc: "PyTorch", value: "PyTorch" },
  { id: 504, desc: "QA - Quality Assurance", value: "QA - Quality Assurance" },
  { id: 505, desc: "Qcodo", value: "Qcodo" },
  { id: 506, desc: "QCubed", value: "QCubed" },
  { id: 507, desc: "Qlikview", value: "Qlikview" },
  { id: 508, desc: "QMake", value: "QMake" },
  { id: 509, desc: "QML", value: "QML" },
  { id: 510, desc: "Quasar", value: "Quasar" },
  { id: 511, desc: "Quixote", value: "Quixote" },
  { id: 512, desc: "R", value: "R" },
  { id: 513, desc: "RabbitMQ", value: "RabbitMQ" },
  { id: 514, desc: "Racket", value: "Racket" },
  { id: 515, desc: "Ragel in Ruby Host", value: "Ragel in Ruby Host" },
  { id: 516, desc: "Ramaze", value: "Ramaze" },
  { id: 517, desc: "RAML", value: "RAML" },
  { id: 518, desc: "Rascal", value: "Rascal" },
  { id: 519, desc: "Ratpack", value: "Ratpack" },
  { id: 520, desc: "RavenDB", value: "RavenDB" },
  { id: 521, desc: "Raw token data", value: "Raw token data" },
  { id: 522, desc: "RDoc", value: "RDoc" },
  { id: 523, desc: "ReactJS", value: "ReactJS" },
  { id: 524, desc: "React Native", value: "React Native" },
  { id: 525, desc: "REALbasic", value: "REALbasic" },
  { id: 526, desc: "Rebol", value: "Rebol" },
  { id: 527, desc: "Red", value: "Red" },
  { id: 528, desc: "Redcode", value: "Redcode" },
  { id: 529, desc: "Redis", value: "Redis" },
  { id: 530, desc: "Redux", value: "Redux" },
  { id: 531, desc: "RenderScript", value: "RenderScript" },
  { id: 532, desc: "RESTful", value: "RESTful" },
  { id: 533, desc: "RestfulX", value: "RestfulX" },
  { id: 534, desc: "Restlet", value: "Restlet" },
  { id: 535, desc: "reStructuredText", value: "reStructuredText" },
  { id: 536, desc: "Revel", value: "Revel" },
  { id: 537, desc: "REXX", value: "REXX" },
  { id: 538, desc: "RHTML", value: "RHTML" },
  { id: 539, desc: "Ring", value: "Ring" },
  { id: 540, desc: "Riot.js", value: "Riot.js" },
  { id: 541, desc: "RMarkdown", value: "RMarkdown" },
  { id: 542, desc: "RobotFramework", value: "RobotFramework" },
  { id: 543, desc: "Roma", value: "Roma" },
  { id: 544, desc: "Rouge", value: "Rouge" },
  { id: 545, desc: "RPM Spec", value: "RPM Spec" },
  { id: 546, desc: "Ruby", value: "Ruby" },
  { id: 547, desc: "Ruby on Rails", value: "Ruby on Rails" },
  { id: 548, desc: "Rum", value: "Rum" },
  { id: 549, desc: "RUNOFF", value: "RUNOFF" },
  { id: 550, desc: "Rust", value: "Rust" },
  { id: 551, desc: "Sage", value: "Sage" },
  { id: 552, desc: "Sails.js", value: "Sails.js" },
  { id: 553, desc: "Salesforce", value: "Salesforce" },
  { id: 554, desc: "SaltStack", value: "SaltStack" },
  { id: 555, desc: "Salvia", value: "Salvia" },
  { id: 556, desc: "SAP", value: "SAP" },
  { id: 557, desc: "SAS", value: "SAS" },
  { id: 558, desc: "Sass", value: "Sass" },
  { id: 559, desc: "Scala", value: "Scala" },
  { id: 560, desc: "Scalatra", value: "Scalatra" },
  { id: 561, desc: "Scaml", value: "Scaml" },
  { id: 562, desc: "Scheme", value: "Scheme" },
  { id: 563, desc: "Scikit-learn", value: "Scikit-learn" },
  { id: 564, desc: "Scilab", value: "Scilab" },
  { id: 565, desc: "SCORM", value: "SCORM" },
  { id: 566, desc: "SCRUM", value: "SCRUM" },
  { id: 567, desc: "SCSS", value: "SCSS" },
  { id: 568, desc: "Seagull", value: "Seagull" },
  { id: 569, desc: "seaside", value: "seaside" },
  { id: 570, desc: "Selenium", value: "Selenium" },
  { id: 571, desc: "Self", value: "Self" },
  { id: 572, desc: "SEO", value: "SEO" },
  { id: 573, desc: "servant", value: "servant" },
  { id: 574, desc: "Server", value: "Server" },
  { id: 575, desc: "Serverless", value: "Serverless" },
  { id: 576, desc: "Sharepoint", value: "Sharepoint" },
  { id: 577, desc: "Shell", value: "Shell" },
  { id: 578, desc: "Shell Script", value: "Shell Script" },
  { id: 579, desc: "ShellSession", value: "ShellSession" },
  { id: 580, desc: "Shen", value: "Shen" },
  { id: 581, desc: "SilverStripe Sapphire", value: "SilverStripe Sapphire" },
  { id: 582, desc: "simplex", value: "simplex" },
  { id: 583, desc: "Sin", value: "Sin" },
  { id: 584, desc: "Sinatra", value: "Sinatra" },
  { id: 585, desc: "Slash", value: "Slash" },
  { id: 586, desc: "Slim", value: "Slim" },
  { id: 587, desc: "Smali", value: "Smali" },
  { id: 588, desc: "Smalltalk", value: "Smalltalk" },
  { id: 589, desc: "Smarty", value: "Smarty" },
  { id: 590, desc: "SMT", value: "SMT" },
  { id: 591, desc: "Snap", value: "Snap" },
  { id: 592, desc: "Solar", value: "Solar" },
  { id: 593, desc: "S.O.L.I.D", value: "S.O.L.I.D" },
  { id: 594, desc: "SourcePawn", value: "SourcePawn" },
  { id: 595, desc: "SPARQL", value: "SPARQL" },
  { id: 596, desc: "Spline Font Database", value: "Spline Font Database" },
  { id: 597, desc: "Spring", value: "Spring" },
  { id: 598, desc: "Spring Boot", value: "Spring Boot" },
  { id: 599, desc: "Spring Cloud", value: "Spring Cloud" },
  { id: 600, desc: "Spring MVC", value: "Spring MVC" },
  { id: 601, desc: "SproutCore", value: "SproutCore" },
  { id: 602, desc: "SQF", value: "SQF" },
  { id: 603, desc: "SQL", value: "SQL" },
  { id: 604, desc: "SQLite", value: "SQLite" },
  { id: 605, desc: "SQLPL", value: "SQLPL" },
  { id: 606, desc: "SQL Server", value: "SQL Server" },
  { id: 607, desc: "SQR", value: "SQR" },
  { id: 608, desc: "Squatting", value: "Squatting" },
  { id: 609, desc: "Squirrel", value: "Squirrel" },
  { id: 610, desc: "SRecode Template", value: "SRecode Template" },
  { id: 611, desc: "Stan", value: "Stan" },
  { id: 612, desc: "Standard ML", value: "Standard ML" },
  { id: 613, desc: "Stata", value: "Stata" },
  { id: 614, desc: "STON", value: "STON" },
  { id: 615, desc: "Stripes", value: "Stripes" },
  { id: 616, desc: "Struts", value: "Struts" },
  { id: 617, desc: "Styled-Components", value: "Styled-Components" },
  { id: 618, desc: "Stylus", value: "Stylus" },
  { id: 619, desc: "Sublime Text Config", value: "Sublime Text Config" },
  { id: 620, desc: "SubRip Text", value: "SubRip Text" },
  { id: 621, desc: "SuperCollider", value: "SuperCollider" },
  { id: 622, desc: "SVG", value: "SVG" },
  { id: 623, desc: "sweetscala", value: "sweetscala" },
  { id: 624, desc: "Swift", value: "Swift" },
  { id: 625, desc: "Swiftlet", value: "Swiftlet" },
  { id: 626, desc: "Swiz", value: "Swiz" },
  { id: 627, desc: "Symfony", value: "Symfony" },
  { id: 628, desc: "SystemVerilog", value: "SystemVerilog" },
  { id: 629, desc: "Tapestry", value: "Tapestry" },
  { id: 630, desc: "Tcl", value: "Tcl" },
  { id: 631, desc: "Tcsh", value: "Tcsh" },
  { id: 632, desc: "TDD", value: "TDD" },
  { id: 633, desc: "Tea", value: "Tea" },
  { id: 634, desc: "TensorFlow", value: "TensorFlow" },
  { id: 635, desc: "Terra", value: "Terra" },
  { id: 636, desc: "Testes automatizados", value: "Testes automatizados" },
  { id: 637, desc: "Testes de Regressão", value: "Testes de Regressão" },
  { id: 638, desc: "Testes Funcionais", value: "Testes Funcionais" },
  { id: 639, desc: "Testes unitários", value: "Testes unitários" },
  { id: 640, desc: "TeX", value: "TeX" },
  { id: 641, desc: "Text", value: "Text" },
  { id: 642, desc: "Textile", value: "Textile" },
  { id: 643, desc: "Thrift", value: "Thrift" },
  { id: 644, desc: "Tipfy", value: "Tipfy" },
  { id: 645, desc: "TI Program", value: "TI Program" },
  { id: 646, desc: "TLA", value: "TLA" },
  { id: 647, desc: "Tomcat", value: "Tomcat" },
  { id: 648, desc: "TOML", value: "TOML" },
  { id: 649, desc: "Tornado", value: "Tornado" },
  { id: 650, desc: "T-SQL", value: "T-SQL" },
  { id: 651, desc: "Turbine", value: "Turbine" },
  { id: 652, desc: "TurboGears", value: "TurboGears" },
  { id: 653, desc: "Turing", value: "Turing" },
  { id: 654, desc: "Turtle", value: "Turtle" },
  { id: 655, desc: "Twig", value: "Twig" },
  { id: 656, desc: "TXL", value: "TXL" },
  { id: 657, desc: "TypeScript", value: "TypeScript" },
  { id: 658, desc: "UKI", value: "UKI" },
  { id: 659, desc: "UML", value: "UML" },
  { id: 660, desc: "Unified Parallel C", value: "Unified Parallel C" },
  { id: 661, desc: "Unity", value: "Unity" },
  { id: 662, desc: "Unity3D Asset", value: "Unity3D Asset" },
  { id: 663, desc: "Unix", value: "Unix" },
  { id: 664, desc: "Uno", value: "Uno" },
  { id: 665, desc: "UnrealScript", value: "UnrealScript" },
  { id: 666, desc: "UrWeb", value: "UrWeb" },
  { id: 667, desc: "Vaadin", value: "Vaadin" },
  { id: 668, desc: "Vala", value: "Vala" },
  { id: 669, desc: "Vanilla", value: "Vanilla" },
  { id: 670, desc: "Vapor", value: "Vapor" },
  { id: 671, desc: "VBA", value: "VBA" },
  { id: 672, desc: "VB .NET", value: "VB .NET" },
  { id: 673, desc: "VCL", value: "VCL" },
  { id: 674, desc: "Verilog", value: "Verilog" },
  { id: 675, desc: "Vert.x", value: "Vert.x" },
  { id: 676, desc: "VHDL", value: "VHDL" },
  { id: 677, desc: "VimL", value: "VimL" },
  { id: 678, desc: "Visual Basic", value: "Visual Basic" },
  { id: 679, desc: "Volt", value: "Volt" },
  { id: 680, desc: "Vork", value: "Vork" },
  { id: 681, desc: "Vroom", value: "Vroom" },
  { id: 682, desc: "VTEX", value: "VTEX" },
  { id: 683, desc: "Vue.js", value: "Vue.js" },
  { id: 684, desc: "Wavefront Material", value: "Wavefront Material" },
  { id: 685, desc: "Wavefront Object", value: "Wavefront Object" },
  { id: 686, desc: "Waves", value: "Waves" },
  { id: 687, desc: "web2py", value: "web2py" },
  { id: 688, desc: "Web API", value: "Web API" },
  { id: 689, desc: "WebGUI", value: "WebGUI" },
  { id: 690, desc: "WebIDL", value: "WebIDL" },
  { id: 691, desc: "Webjure", value: "Webjure" },
  { id: 692, desc: "Web Ontology Language", value: "Web Ontology Language" },
  { id: 693, desc: "WebRTC", value: "WebRTC" },
  { id: 694, desc: "Web Services", value: "Web Services" },
  { id: 695, desc: "Wee", value: "Wee" },
  { id: 696, desc: "Wicket", value: "Wicket" },
  { id: 697, desc: "Wisp", value: "Wisp" },
  { id: 698, desc: "WooCommerce", value: "WooCommerce" },
  { id: 699, desc: "WordPress", value: "WordPress" },
  {
    id: 700,
    desc: "World of Warcraft Addon Data",
    value: "World of Warcraft Addon Data"
  },
  { id: 701, desc: "WPF", value: "WPF" },
  { id: 702, desc: "X10", value: "X10" },
  { id: 703, desc: "Xamarin", value: "Xamarin" },
  { id: 704, desc: "xBase", value: "xBase" },
  { id: 705, desc: "XC", value: "XC" },
  { id: 706, desc: "Xitrum", value: "Xitrum" },
  { id: 707, desc: "XML", value: "XML" },
  { id: 708, desc: "XMPP", value: "XMPP" },
  { id: 709, desc: "Xojo", value: "Xojo" },
  { id: 710, desc: "XPages", value: "XPages" },
  { id: 711, desc: "XProc", value: "XProc" },
  { id: 712, desc: "XQuery", value: "XQuery" },
  { id: 713, desc: "XS", value: "XS" },
  { id: 714, desc: "XSLT", value: "XSLT" },
  { id: 715, desc: "Xtend", value: "Xtend" },
  { id: 716, desc: "Xyster", value: "Xyster" },
  { id: 717, desc: "Yacc", value: "Yacc" },
  { id: 718, desc: "YAML", value: "YAML" },
  { id: 719, desc: "YANG", value: "YANG" },
  { id: 720, desc: "Yesod", value: "Yesod" },
  { id: 721, desc: "Yii", value: "Yii" },
  { id: 722, desc: "Zend", value: "Zend" },
  { id: 723, desc: "Zephir", value: "Zephir" },
  { id: 724, desc: "Zimpl", value: "Zimpl" },
  { id: 725, desc: "ZK", value: "ZK" },
  { id: 726, desc: "Zope", value: "Zope" },
  { id: 727, desc: "Zotonic", value: "Zotonic" }
];

export default Skills;
