const Naturalidade = [
  { id: 0, desc: "Selecione sua naturalidade", value: "null" },
  { id: 1, desc: "Acre", value: "AC" },
  { id: 2, desc: "Alagoas", value: "AL" },
  { id: 3, desc: "Amazona", value: "AM" },
  { id: 4, desc: "Amapá", value: "AP" },
  { id: 5, desc: "Bahia", value: "BA" },
  { id: 6, desc: "Ceará", value: "CE" },
  { id: 7, desc: "Distrito Federal	", value: "DF" },
  { id: 8, desc: "Espírito Santo	", value: "ES" },
  { id: 9, desc: "Goiás	", value: "GO" },
  { id: 10, desc: "Maranhão	", value: "MA" },
  { id: 11, desc: "Minas Gerais	", value: "MG" },
  { id: 12, desc: "Mato Grosso do Sul	", value: "MS" },
  { id: 13, desc: "Mato Grosso	", value: "MT" },
  { id: 14, desc: "Pará	", value: "PA" },
  { id: 15, desc: "Paraíba	", value: "PB" },
  { id: 16, desc: "Pernambuco	", value: "PE" },
  { id: 17, desc: "Piauí	", value: "PI" },
  { id: 18, desc: "Paraná	", value: "PR" },
  { id: 19, desc: "Rio de Janeiro	", value: "RJ" },
  { id: 20, desc: "Rio Grande do Norte	", value: "RN" },
  { id: 21, desc: "Rondônia	", value: "RO" },
  { id: 22, desc: "Roraima	", value: "RR" },
  { id: 23, desc: "Rio Grande do Sul	", value: "RS" },
  { id: 24, desc: "Santa Catarina", value: "SC" },
  { id: 25, desc: "Sergipe", value: "SE" },
  { id: 26, desc: "São Paulo", value: "SP" },
  { id: 27, desc: "Tocantins", value: "TO" },
  { id: 28, desc: "Internacional", value: "IN" }
] as const;

export default Naturalidade;
